# devtree-front/Dockerfile
# Etapa de instalación de dependencias
FROM node:22-alpine3.20 AS dev-dependencies
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# Etapa de desarrollo
FROM node:22-alpine3.20 AS dev
WORKDIR /app
COPY --from=dev-dependencies /app/node_modules ./node_modules
COPY . .
EXPOSE 3031
CMD ["npm", "run", "dev"]